language: ruby
rvm:
  - 2.1

# assumes gems in Gemfile have been installed already
script: jekyll build && htmlproof ./_site --href-ignore /http:\/\/www\.baseball\-reference\.com/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
