language: ruby
rvm:
  - 2.1
addons:
  apt:
    packages:
      - tree
      - jq

before_script:
  - DATE=`date` jq '{ts: now, date: env.DATE, branch: env.TRAVIS_BRANCH, build_id: env.TRAVIS_BUILD_ID, build_number: env.TRAVIS_BUILD_NUMBER, commit: env.TRAVIS_COMMIT, commit_message: env.TREAVIS_COMMIT_MESSAGE, commit_range: env.TRAVIS_COMMIT_RANGE, event_type: env.TRAVIS_EVENT_TYPE, job_id: env.TRAVIS_JOB_ID, job_number: env.TRAVIS_JOB_NUMBER, repo_slug: env.TRAVIS_REPO_SLUG, sudo: env.TRAVIS_SUDO}' > build.json

# assumes gems in Gemfile have been installed already
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --href-ignore /^http:\/\/www\.baseball\-/,/^http:\/\/substack\.net/,/^https:\/\/tomhummel\.com\/tag/
  - tree -a ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: _site
  bucket: "tomhummel.com"
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack:
    rooms:
      - "${SLACK_TOKEN}#ops"
    on_pull_requests: true
