language: ruby
rvm:
  - 2.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tree
  - sudo wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq
  - sudo chmod o+x /usr/local/bin/jq

before_script:
  - jq --version
  - make ci.json

# assumes gems in Gemfile have been installed already
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --href-ignore /^http:\/\/www\.baseball\-/,/^http:\/\/substack\.net/,/^https:\/\/tomhummel\.com\/tag/
  - tree -a ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: _site
  bucket: "tomhummel.com"
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack:
    rooms:
      - "${SLACK_TOKEN}#ops"
    on_pull_requests: true
