safe:        false

source:      .
destination: ./_site
plugins_dir:     ./_plugins

future:      false
lsi:         false
highlighter:    pygments

markdown: rdiscount
rdiscount:
  extensions: [smart]

permalink:   pretty

exclude:    ["vendor","Gemfile*"]
paginate:   5

# gem install jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag

name: Tom Hummel
twitter: tphummel
github_user: tphummel
gravatar_url: https://www.gravatar.com/avatar/e773e8aca4e33a69be538a75d700ff30

# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex

gems:
  - jekyll-paginate
  - jekyll-sitemap
