safe:        false
auto:        false
server:      false

source:      .
destination: ./_site
plugins:     ./_plugins

future:      false
lsi:         false
pygments:    false
markdown:    maruku
permalink:   pretty

exclude: ["sync.coffee"]

# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex