safe:        false
auto:        false
server:      false

source:      .
destination: ./_site
plugins:     ./_plugins

future:      false
lsi:         false
pygments:    false
markdown:    maruku
permalink:   pretty

exclude:    ["package.json", "node_modules", "script", "doc", "bin", "log", "_gist_cache"]
paginate:   5

# gem install jekyll-tagging
tag_page_layout: tag_page 
tag_page_dir: tag


# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex